# Dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

RUN pip install setuptools
# RUN pip install -r /app/src/requrements.txt
RUN python setup.py install

# Указание порта
EXPOSE 9090