version: '3.8'

services:
  router:
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: router
    hostname: router
    command: python -m debugpy --listen 0.0.0.0:5678 -m router.cli --port 9090 --host 0.0.0.0 --debug
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    ports:
      - "9090:9090"
      - "5678:5678"
    depends_on:
      - redis

  syncer:
    build:
      context: .
      dockerfile: Dockerfile.syncer
    container_name: syncer
    command: python /app/tools/syncaccs.py https://analitika-wb-ozon.pro/get_all_tokens router:9090/router/accounts auth 10 15
    volumes:
      - .:/app
    depends_on:
      - router

  redis:
    image: redis:alpine
    container_name: ro_redis